
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'try to add using FlutLab Firebase Configuration',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlMC-Xw_Dc3Xjr1lCxrM0xbZr79pUz_fo',
    iosBundleId: 'com.myproject',
    appId: '1:772702756793:ios:033e3c5939e8dce43f2068',
    storageBucket: 'myproject-334f7.appspot.com',
    messagingSenderId: '772702756793',
    iosClientId: 'undefined',
    projectId: 'myproject-334f7'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBizvVVpLI3d1u0iVXRVkp12Zm9UlwPptg',
    appId: '1:772702756793:android:a8d71b06b8573ef53f2068',
    messagingSenderId: '772702756793',
    projectId: 'myproject-334f7',
    storageBucket: 'myproject-334f7.appspot.com'
  );
}
